apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backstage
  namespace: backstage
spec:
  template:
    spec:
      containers:
        - name: backstage
          image: ghcr.io/igfurlan/backstage:sha-b1c1a25
